// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrvptdrstohszeewchiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ydnB0ZHJzdG9oc3plZXdjaGl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5NzkzNDIsImV4cCI6MjA1MDU1NTM0Mn0.m5HA-qK0X3w_3E2BUENqG9KVnLh7_P5z8NlAD44l538";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);